name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/xYc4t/android_kernel_xiaomi_mt6893
          kernel-branch: lineage-22.2
          config: chopin_user_defconfig
          arch: arm64
          other-clang-url: https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/10032024/neutron-clang-10032024.tar.zst
          extra-cmd: 'CC="clang --gcc-toolchain=$HOME/clang" CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-'
          anykernel3: true
