name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/xYc4t/android_kernel_xiaomi_mt6893
          kernel-branch: dev3
          config: chopin_user_defconfig
          arch: arm64
          aosp-clang: true
          aosp-clang-version: r547379
          aosp-gcc: true
          anykernel3: true
          extra-cmd: LLVM=1 LLVM_IAS=1
