name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/xYc4t/android_kernel_xiaomi_mt6893
          kernel-branch: lineage-22.2
          config: chopin_user_defconfig
          arch: arm64
          other-clang-url: https://github.com/ZyCromerZ/Clang/releases/download/22.0.0git-20250805-release/Clang-22.0.0git-20250805.tar.gz
          aosp-gcc: true
          anykernel3: true
          extra-cmd: LLVM_IAS=1
