name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/xYc4t/kernel_xiaomi_chopin
          kernel-branch: main
          config: chopin_defconfig
          arch: arm64
          aosp-clang: true
          aosp-clang-version: r547379
          aosp-gcc: true
          anykernel3: true
          extra-make-args: '["LLVM=1", "LLVM_IAS=1", "LD=ld.lld"]'
