name: Build Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel
        uses: actions/checkout@v3

      - name: Setup Clang
        run: |
          wget https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/10032024/neutron-clang-10032024.tar.zst
          tar -I zstd -xf neutron-clang-10032024.tar.zst
          echo "$PWD/neutron-clang-10032024/bin" >> $GITHUB_PATH

      - name: Download AnyKernel3
        run: |
          wget -O anykernel.zip https://github.com/AnyKernel/AnyKernel3/archive/refs/heads/master.zip
          unzip anykernel.zip
          mv AnyKernel3-master anykernel

      - name: Configure Kernel
        run: |
          cd android_kernel_xiaomi_mt6893
          make O=out ARCH=arm64 chopin_user_defconfig

      - name: Build Kernel
        run: |
          cd android_kernel_xiaomi_mt6893
          make O=out ARCH=arm64 -j$(nproc)

      - name: Package AnyKernel3
        run: |
          KERNEL_IMG=$(pwd)/android_kernel_xiaomi_mt6893/out/arch/arm64/boot/Image.gz-dtb
          cp $KERNEL_IMG anykernel/
          cd anykernel
          zip -r kernel.zip *

      - name: Upload AnyKernel ZIP
        uses: actions/upload-artifact@v4
        with:
          name: kernel-zip
          path: anykernel/kernel.zip
          retention-days: 7
